function [ L_h ] = Hydrofoil_Lift( V, h, Pars )
%Hydrofoil_Lift - Computes the lift generated by the hydrofoil
%   Inputs:
%   V - velocity
%   h - water depth measured from bottom of hydrofoil
%   Pars - all the necessary parameters. Must contain:
%       H_h - the distance between the hydrofoil and the hull
%       Gamma - the dihedral angle of the hydrofoil (also describes hull
%           triangular part)
%       rho_a - air density
%       W - width of the hull (and hydrofoil)
%       c - hydrofoil chord
H_V = 0.5*Pars.W_h*sin(Pars.Gamma);

if h>=H_V+Pars.c_h
    CL_h = 0.8;
    S_hs_proj = Pars.W_h*Pars.c_h;
elseif h>= H_V
    CL_h = 0.4+0.4*(h-H_V)/Pars.c_h;
    S_hs_proj = Pars.W_h*Pars.c_h;
else
    CL_h = 0.4;
    S_hs_proj = Pars.W_h*Pars.c_h*h/H_V;
end

if(S_hs_proj<0)
    S_hs_proj = 0;
end

L_h = 0.5*Pars.rho_w*V^2*CL_h*S_hs_proj;    
end

